yarnPath: .yarn/releases/yarn-3.1.1.cjs

npmScopes:
  shsusac:
    npmRegistryServer: "https://npm.pkg.github.com"

packageExtensions:
  #SemVer
  semantic-release-plugin-decorators@*:
    peerDependencies:
      "@semantic-release/changelog": "*"
      "@semantic-release/git": "*"
      "@semantic-release/github": "*"
      "@semantic-release/npm": "*"
      "@semantic-release/release-notes-generator": "*"
    peerDependenciesMeta:
      "@semantic-release/changelog":
        optional: true
      "@semantic-release/git":
        optional: true
      "@semantic-release/github":
        optional: true
      "@semantic-release/npm":
        optional: true
      "@semantic-release/release-notes-generator":
        optional: true
  semantic-release@*:
    peerDependencies:
      "@semantic-release/changelog": "*"
      "@semantic-release/git": "*"
      semantic-release-monorepo: "*"
    peerDependenciesMeta:
      "@semantic-release/changelog":
        optional: true
      "@semantic-release/git":
        optional: true
      semantic-release-monorepo:
        optional: true


  #Image handlers
  optimized-images-loader@*:
    dependencies:
      webpack: "*"
  next-optimized-images@*:
    dependencies:
      webpack: "*"


  #Firebase compat dependencies
  "@firebase/analytics-compat@*":
    dependencies:
      "@firebase/app": "*"
  "@firebase/app-check-compat@*":
    dependencies:
      "@firebase/app": "*"
  "@firebase/auth-compat@*":
    dependencies:
      "@firebase/app": "*"
      "@firebase/app-types": "*"
  "@firebase/database-compat@*":
    dependencies:
      "@firebase/app-compat": "*"
  "@firebase/database@*":
    dependencies:
      "@firebase/app": "*"
      "@firebase/app-types": "*"
  "@firebase/firestore-compat@*":
    dependencies:
      "@firebase/app": "*"
      "@firebase/app-types": "*"
  "@firebase/functions-compat@*":
    dependencies:
      "@firebase/app": "*"
  "@firebase/functions@*":
    dependencies:
      "@firebase/app-types": "*"
  "@firebase/messaging-compat@*":
    dependencies:
      "@firebase/app": "*"
  "@firebase/performance-compat@*":
    dependencies:
      "@firebase/app": "*"
  "@firebase/remote-config-compat@*":
    dependencies:
      "@firebase/app": "*"
  "@firebase/storage-compat@*":
    dependencies:
      "@firebase/app": "*"
      "@firebase/app-types": "*"