name: Deploy release to firebase
on:
  release:
    types: [released]

jobs:
  deploy_firestore:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        if: ${{ !env.ACT }}
        uses: actions/checkout@v2
        with:
          lfs: false

      - name: Deploy Firestore
        if: ${{ !env.ACT }}
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only firestore
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SUBMAN2 }}

  deploy_firebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Setup Node, Yarn and Cached Dependencies
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --immutable --check-cache

      - name: Build
        run: yarn gulp build

      - name: Deploy Hosting
        if: ${{ !env.ACT }}
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SUBMAN2 }}
          channelId: live
          projectId: subman2