name: Deploy release to firebase
on:
  release:
    types: [released]

jobs:
  deploy_firestore:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        if: ${{ !env.ACT }}
        uses: actions/checkout@v2
        with:
          lfs: false

      - name: Deploy Firestore
        if: ${{ !env.ACT }}
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only firestore
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SUBMAN2 }}

  deploy_hosting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Check if build artifacts already cached
        if: ${{ !env.ACT }}
        id: build_cache
        uses: actions/cache@v2
        with:
          path: out
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}-hash-${{ github.sha }}

      - name: Setup Node and Cached Dependencies
        if: steps.build_cache.outputs.cache-hit != 'true' && ${{ !env.ACT }}
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'

      - name: Install Dependencies
        if: steps.build_cache.outputs.cache-hit != 'true'
        run: yarn install --immutable --check-cache

      - name: Build
        if: steps.build_cache.outputs.cache-hit != 'true'
        run: yarn gulp build

      - name: Deploy Hosting
        if: ${{ !env.ACT }}
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SUBMAN2 }}
          channelId: live
          projectId: subman2