name: Deploy Preview to Firebase Hosting on PR
"on":
  pull_request:

jobs:
  deploy_preview:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Install Yarn
        if: ${{ env.ACT }}
        run: npm install --global yarn

      - name: Setup Node and Cached Dependencies
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install --immutable --check-cache

      - name: Build
        run: yarn gulp build

      #- name: Test
      #  run: yarn run test

      - uses: FirebaseExtended/action-hosting-deploy@v0
        if: ${{ !env.ACT }}
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_SUBMAN2 }}"
          projectId: subman2
